defined wfmux default configuration

diff --git a/src/wfmux b/src/wfmux
--- a/src/wfmux
+++ b/src/wfmux
@@ -8,10 +8,12 @@ config_file="${XDG_CONFIG_HOME:-"$HOME/.config"}"
 wfmux_config="${config_file%%/}/wfmux/wfmux.conf"
 
 use_xdg=yes
-automater=entr
+runner=entr
+restarter=entr
+restarter_templates="$HOME/.config/wfmux/stemplate"
+runner_templates="$HOME/.config/wfmux/rtemplate"
 explorer=nnn
 searcher=fzf
-automation_templates="$HOME/.config/wfmux/template"
 window_attributes_rest=20x20+10+20
 window_attributes_file_selector=20x20+10+20
 
@@ -28,14 +30,15 @@ programs=$(cat <<-EOF
 	video:    ffmpeg
 	audio:    aplay
 	image:    feh
-	database: prog_name
+	database: program_name
 	EOF
 )
 
 usage() {
 	cat<<EOF
 Build an awesome dev workflow with tmux, fzf, nnn, and entr.
-usage: wfmux operation_name [options]
+usage: wfmux operation_name [-c|-config|--config config_file]
+       wfmux [-h|-c|-help|-config|--help|--config]
 
 Options:
      -h, -help, --help            print this help message.
@@ -50,6 +53,7 @@ operation_name:
               project.
     commit    add to the index and commit changes to local repository.
     push      push to the preconfigured remote repositories.
+	switch    fuzzyly switch between branches of your local repository.
 EOF
 }
 
@@ -77,7 +81,8 @@ main() {
 						wfmux_config=$3
 						[ -e "$wfmux_config" ] || die "'$wfmux_config' does not exist"
 						[ -r "$wfmux_config" ] || die "no permission to read '$wfmux_config'"
-						. $wfmux_config || die "could not source configuration file"
+						. $wfmux_config        || die "could not source configuration file"
+						check_config_variables
 						eval "$1" ;;
 					*)
 						die "$2" "$error_message" ;;
@@ -119,9 +124,12 @@ check_config_variables() {
 		[ $found = false ] && die "$error_message" "'$dependency' isn't found"
 	done
 
-	# check if these project dirs exist
+	# check if project dirs exist
 	IFS=$'\n'
-	for dir in $project_directory; do [ -d "$dir" ] || die "$error_message" "'$dir' isn't a directory"; done
+	for dir in $project_directory; do
+		[ -d "$dir" ] || die "$error_message" "'$dir' isn't a directory"
+		[ -r "$dir" ] || die "$error_message" "cannot list content of '$dir'"
+	done
 	IFS=$OLD_IFS
 }
 
