done with func_rwatcher()
implemented func_(d|e)watcher() via a wrapper __ed_watcher()

diff --git a/src/wfmux b/src/wfmux
--- a/src/wfmux
+++ b/src/wfmux
@@ -13,7 +13,7 @@ readonly unset_ansi='\033[0m'
 readonly program=${0##*/}
 readonly config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}
 readonly wfmux_config_dir="${config_dir%%/}/wfmux"
-readonly runs="$wfmux_config_dir/runs"
+readonly commands="$wfmux_config_dir/commands"
 readonly cache_dir=${XDG_CACHE_HOME:-"$HOME/.cache"}
 readonly cache="${cache_dir%%/}/wfmux"
 readonly cache_pl="${cache_dir}/wfmux.pl"
@@ -429,7 +429,7 @@ _setup_session() {
 	if [ -f "$watch_config" ]
 	then
 		local fifo
-		for pairs in `cat "$watch_config" | sed -ne 's/^s+:\[\(.*\)\] *\(.\+\) *$/(\1)\2/p'`
+		for pairs in `cat "$watch_config" | sed -ne 's/^s+\[\(.*\)\]: *\(.\+\) *$/(\1)\2/p'`
 		do
 			local cmd=${pairs#(*)}
 			local watcher_name=${pairs%%)*}
@@ -442,7 +442,7 @@ _setup_session() {
 
 			{ trap '' HUP
 			  cat "$watch_config" \
-				| sed -ne "/^s+:[$watcher_name]/,/^e:[$watcher_name]/p" \
+				| sed -ne "/^s+\[$watcher_name\]:/,/^e\[$watcher_name\]/p" \
 				| tail -n +2 \
 				| sed '$d' \
 				| 
@@ -633,7 +633,7 @@ func_select() {
 	if [ -n "$command" ]
 	then
 		# start from the most active, ignore the previous one
-		for window_index in $(tmux list-windows -F '#I:#{window_active}' | awk -F[':'] '$2 == 1{pass = 1}; pass == 1{print $1}')
+		for window_index in `tmux list-windows -F '#I:#{window_active}' | awk -F[':'] '$2 == 1{pass = 1}; pass == 1{print $1}'`
 		do
 			local panes=$(tmux list-panes -t "$window_index" -F '#{pane_current_command}:#P:#{pane_active}')
 			local bash_panes=$(printf "$panes" | grep "^${sh:-bash}:")
@@ -819,7 +819,7 @@ __push() {
 # Add a new watcher to the watcher list
 func_awatcher() {
 	local watcher_name
-	local watch_config="$session_dir/`__get_cur_session`"
+	local watch_config="$session_dir/`__get_cur_session`/watch"
 	local project_dir=`__get_project_dir`
 
 	printf "Give a name to your watcher: "
@@ -830,8 +830,7 @@ func_awatcher() {
 		# Check if this name already exists in the watcher list
 		if [ -f "$watch_config" ]
 		then
-			cat "$watch_config" | grep -q "s[-+]:\[$watcher_name\]"
-			test $? -eq 0 && return
+			cat "$watch_config" | grep -q "s[-+]:\[$watcher_name\]" && return
 		fi
 
 		local files=$(
@@ -841,42 +840,111 @@ func_awatcher() {
 
 		if [ -n "$files" ]
 		then
-			if [ -r "$runs" ]
+			printf "\033[1;4m"
+			if [ -r "$commands" ]
 			then
-				local cmd=$(cat "$runs" | eval "$searcher")
-				echo "writing to $watch_config"
+				local cmd=$(cat "$commands" | grep -v '^[\t ]*\(#.*\)\?$' | eval "$searcher")
 				cat <<-EOF >>"$watch_config"
 
-				s+[$watcher_name] $cmd
+				s+[$watcher_name]: $cmd
 				$files
 				e[$watcher_name]
 				EOF
-				printf "\033[1;${dash_color}m"
+				printf "\033[1;3${dash_color}m"
 				printf "'${watcher_name}' was successfully added to the list of watchers\n"
 			else
 				printf "\033[1;31m"
-				printf "Cannot find the list of commands.\n" >&2
-				printf "put them at '$runs'\n" >&2
+				printf "Could not find the list of commands.\n" >&2
+				printf "these commands should be located at '$commands'\n" >&2
 			fi
-			printf "\033[0m"
+			printf "\033[0m\033[0m"
+
 			__input_to_exit
 		fi
 	fi
 }
 
-# disable watchers, don't run this watcher when creating tmux sessions
-func_dwatcher() {
-	:;
+# remove watchers from the watcher list
+func_rwatcher() {
+	local watcher_name
+	local project_session="$session_dir/`__get_cur_session`"
+	local watch_config="$project_session/watch"
+
+	if [ -r "$watch_config" -a -s "$watch_config" ]
+	then
+		watcher_name=$(cat "$watch_config" | sed -ne 's/^s[-+]\[\(\w*\)\]:.*$/\1/p')
+		if [ -n "$watcher_name" ]
+		then
+			watcher_name=$(printf "$watcher_name" | eval "$searcher")
+			if [ -n "$watcher_name" ]
+			then
+				printf "\033[1;4m"
+				if cat "$watch_config" | grep -q "^e\[$watcher_name\]"
+				then
+					sed -i "/^s+\[$watcher_name\]:/,/^e\[$watcher_name\]/d" "$watch_config"
+					if [ $? -eq 0 ]
+					then
+						if [ -r "$project_session/$watcher_name.pid" ]
+						then
+							pid=$(cat "$project_session/$watcher_name.pid")
+							kill -KILL "$pid" >/dev/null 2>&1
+						fi
+						printf "\033[1;3${dash_color}m"
+						printf "Watcher '$watcher_name' successfully deleted\n"
+					else
+						printf "\033[1;31m"
+						printf "Could not delete watcher\n"
+					fi
+				else
+					printf "\033[1;31m"
+					printf "Error: could not find scope of definition of '$watcher_name'\n"
+				fi
+				printf "\033[0m\033[0m"
+			fi
+		else
+			printf "you do not have any watcher\n"
+		fi
+
+		__input_to_exit
+	fi
+}
+
+__ed_watcher() {
+	local state=$1
+	local to=disable
+	local watcher_name
+	local project_session="$session_dir/`__get_cur_session`"
+	local watch_config="$project_session/watch"
+
+	[ x$state = x"+" ] && to=enable
+	if [ -r "$watch_config" -a -s "$watch_config" ]
+	then
+		watcher_name=$(cat "$watch_config" | sed -ne 's/^s[-+]\[\(\w*\)\]:.*$/\1/p')
+		if [ -n "$watcher_name" ]
+		then
+			watcher_name=$(printf "$watcher_name" | eval "$searcher")
+			if [ -n "$watcher_name" ]
+			then
+				printf "\033[4m\033[3{$dash_color}m"
+				sed -ie "s/^s.[$watcher_name]/^s$state[$watcher_name]/" "$watch_config"
+				printf "Watcher '$watcher_name' ${to}d\n"
+
+				printf "\033[0m\033[0m"
+			fi
+		else
+			printf "you do not have any watcher\n"
+		fi
+	fi
 }
 
 # enable watchers, should run when creating tmux session
-func_ewatchers() {
-	:;
+func_ewatcher() {
+	__ed_watcher +
 }
 
-# remove watchers from the watcher list
+# disable watchers, don't run this watcher when creating tmux sessions
 func_rwatchers() {
-	:;
+	__ed_watcher -
 }
 
 # fancy view of the watchers
