dump/tmux(): output wfmux's tmux configuration, check_config_variables(): valid input data from wfmux configuration file

diff --git a/src/wfmux b/src/wfmux
--- a/src/wfmux
+++ b/src/wfmux
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/dash
 
 #set -x
 set -ue
@@ -12,11 +12,14 @@ readonly bold='\033[1m'
 readonly unset_ansi='\033[0m'
 readonly program=${0##*/}
 readonly config_dir="${XDG_CONFIG_HOME:-"$HOME/.config"}"
-readonly profiles="${config_dir%%/}/wfmux/profiles"
+readonly wfmux_config_dir="${config_dir%%/}/wfmux/"
 readonly cache_dir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
-readonly cache="${cache_dir%%/}/wfmux/wfmux"
+readonly cache="${cache_dir%%/}/wfmux"
+readonly cache_pl="${cache_dir}/wfmux.pl"
 readonly session_dir="${cache_dir%%/}wfmux/sessions"
 readonly tmux_conf="$HOME/.tmux.conf"
+
+mkdir -p "$config_dir" "$cache_dir" "$cache" "$session_dir" "$wfmux_config_dir"
 
 readonly logo_ls=$(cat <<EOF
 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx┌────────────
@@ -81,7 +84,7 @@ window_attributes_rest=20x20+10+20
 window_attributes_file_selector=20x20+10+20
 window_attributes_input_box=20x20+10+20
 tbind_ops==
-tbind_explorer=BSpace
+tbind_explore=BSpace
 tbind_select=Enter
 
 project_directory=$(cat <<-EOF
@@ -129,43 +132,47 @@ EOF
 }
 
 die() {
-	printf "$*\n"
+	printf "$*\n" >&2
 	exit 1
 }
 
 main() {
-	operation=
-	gave_config=false
+	local operation=
+	local gave_config=false
 
 	[ $# -eq 0 ] && usage 1
 	until [ $# -eq 0 ]
 	do
-		case $1 in
-			-h|-help|--help)
-				usage 0
-				;;
-			-c|-config|--config)
-				[ $# -eq 1 ] && wfmux_config=$2 || usage 1
-				gave_config=true
-				shift
-				;;
-			push|commit|select|explore|auto|open)
-				operation=$1
-				if [ -f "$wfmux_config" ]
-				then
-					[ -r "$wfmux_config" ] || die "no permission to read '$wfmux_config'"
-					. $wfmux_config        || die "could not source configuration file"
-				fi
-				;;
-			*)
-				die "'$1' is an unrecognized option, please try \`$program --help'"
-				;;
+		case "$1" in
+		-h|-help|--help)
+			usage 0 ;;
+		-c|-config|--config)
+			[ $# -eq 1 ] && wfmux_config=$2 || usage 1
+			gave_config=true
+			shift ;;
+		push|commit|select|explore|auto|open|tmux|dump|ops)
+			operation=$1
+			if [ -f "$wfmux_config" ]
+			then
+				[ -r "$wfmux_config" ] || die "no permission to read '$wfmux_config'"
+				. $wfmux_config        || die "could not source configuration file"
+			fi ;;
+		*)
+			die "'$1' is an unrecognized option, please try \`$program --help'" ;;
 		esac
 		shift
 	done
-	## [ $gave_config = true ] && 
-	#check_config_variables
-	eval "$operation"
+	if [ $gave_config = true ]
+	then
+		check_config_variables
+	else
+		# use default config "~/.config/wfmux.conf" is possible
+		if [ -f "$wfmux_config" -a -r "$wfmux_config" ]
+		then
+			check_config_variables
+		fi
+	fi
+	eval "func_$operation"
 }
 
 ## Check if variables are unset or null	and if set then
@@ -173,8 +180,9 @@ main() {
 ## we won't have to rely on `set -u`, we would want to output a custom 
 ## error message if one of these variables aren't set/sane.
 check_config_variables() {
-	_error="$program: ('$config_file'):"
-	for para in use_xdg \
+	_error="$program: ('$wfmux_config'):"
+	for para in \
+		         use_xdg \
 		         runner \
 		         searcher \
 		         explorer \
@@ -193,45 +201,31 @@ check_config_variables() {
 		fi
 	done
 
-	config_die() {
+	_config_die() {
 		die "$_error invalid value assigned to '$1'"
 	}
 
-	# Check for valid bindings to be used to generate tmux config for wfmux
-	for i in tbind_ops tbind_select tbind_explore
-	do
-		eval "key=\${#$i}"
-		if [ $key -ne 1 ]
-		then
-			die "'$i' should be a single character"
-		fi
-		if [ -n "$(expr "$key" : '[^[A-Za-z]]$')" ]
-		then
-			config_die "$i"
-		fi
-	done
-
 	## Check if we got sane values
-	window_regex='[[:digit:]]\+x[[:digit:]]+\+[[:digit:]]+\+[[:digit:]]+$'
 	{
-		expr "$window_attributes_rest"          : "$window_regex" || config_die window_attributes_rest
-		expr "$window_attributes_file_selector" : "$window_regex" || config_die window_attributes_file_selector
-		expr "$window_attributes_input_box"     : "$window_regex" || config_die window_attributes_input_box
-		expr "$use_xdg"                         : 'yes|no$'       || config_die use_xdg
-		expr "$dash_color"                      : '[0-9]$'        || config_die dash_color
+		window_regex='[[:digit:]]\+x[[:digit:]]\++[[:digit:]]\++[[:digit:]]\+$'
+		expr "$window_attributes_rest"          : "$window_regex" || _config_die window_attributes_rest
+		expr "$window_attributes_file_selector" : "$window_regex" || _config_die window_attributes_file_selector
+		expr "$window_attributes_input_box"     : "$window_regex" || _config_die window_attributes_input_box
+		expr "$use_xdg"                         : 'true\|false$'  || _config_die use_xdg
+		expr "$dash_color"                      : '[0-9]$'        || _config_die dash_color
 	} >/dev/null
 
-	for cv in explorer runner searcher
+	for i in explorer runner searcher
 	do
-		command -v "$(eval "printf \${#$cv}")" || die "$error_ '$cv' not found"
+		eval "command -v" "\${$i} >/dev/null" || die "$_error '$i' not found"
 	done
 
 	# IFS=$'\n' won't expand '\n' on dash, thus `for i in $pro...' or a simple use of `$pro..` might not work as intended
 	printf "$project_directory" |
-	while read cv
+	while read i
 	do
-		[ -d "$cv" ] || die "$_error '$cv' is not a directory"
-		[ -r "$cv" ] || die "$_error cannot list content of '$cv'"
+		[ -d "$i" ] || die "$_error '$i' is not a directory"
+		[ -r "$i" ] || die "$_error cannot list content of '$i'"
 	done
 }
 
@@ -255,7 +249,7 @@ display_dashboard() {
 			The following are tmux bindings related to WFMUX.
 
 			M-$tbind_select: fuzzyly open project files
-			M-$tbind_explorer: open file manager
+			M-$tbind_explore: open file manager
 			M-$tbind_ops: fuzzyly select other wfmux operations
 
 			input any key to exit dashboard
@@ -305,17 +299,17 @@ display_dashboard() {
 
 			printf "${clear_screen}${put_color}${bold}"
 			eval 'printf "$logo_'$_size'"' | {
-				while read line
+				while read i
 				do
-					_print $y $x "$(printf "$line" | tr 'x' ' ')"
+					_print $y $x "$(printf "$i" | tr 'x' ' ')"
 					y="$(($y+1))"
 				done
 
 				printf "$unset_ansi"
-				_gen_key_helper | while read line
+				_gen_key_helper | while read i
 				do
 					y="$(($y+1))"
-					_print $y $gen_x "$line"
+					_print $y $gen_x "$i"
 				done
 			}
 		done
@@ -331,7 +325,7 @@ display_dashboard() {
 
 ## select a project and open a tmux session
 ## refer to usage() function for more information
-open() {
+func_open() {
 	if tmux list-sessions >/dev/null 2>&1
 	then
 		printf "Choose an existing session to attach\n\n"
@@ -353,8 +347,7 @@ open() {
 		then
 			ran_find=
 			must_find=false
-			##### changing timestamp for $cache will always make `[ "$p" -nt "$cache" ]' yield true
-			[ -e "$cache" ] || touch "$cache"
+			[ -e "$cache_pl" ] || touch "$cache_pl"
 
 			find_git_repos() {
 				find "$1" -mindepth 2 -type d -iname '.git' -exec expr '{}' : '\(.*\)/.git$' \;
@@ -364,23 +357,23 @@ open() {
 				printf "$project_directory" | {
 					while read p
 					do
-						if [ "$p" -nt "$cache" ]
+						if [ "$p" -nt "$cache_pl" ]
 						then
 							must_find=true
 						fi
 						$must_find || { set -- "$@" "$p"; continue; }
-						find_git_repos "$p" | tee ${ran_find--a} "$cache"
+						find_git_repos "$p" | tee ${ran_find--a} "$cache_pl"
 						unset ran_find
 					done
 					if $must_find
 					then # go through the rest
-						for p in "$@"; do find_git_repos "$p" | tee -a "$cache"; done
+						for p in "$@"; do find_git_repos "$p" | tee -a "$cache_pl"; done
 					fi
 				}
 			)
 			if [ -z "$project_list" ]
 			then
-				project_list="$(cat "$cache")"
+				project_list="$(cat "$cache_pl")"
 			fi
 
 			project_name=$(
@@ -391,7 +384,7 @@ open() {
 			)
 			[ -z "$project_name" ] && return
 
-			session_name="$(printf "$project_list" | sed "$(expr "$project_name" : '\[\([0-9]\+\)\]:.*$')p" | tr / - | hide_dots)"
+			session_name="$(printf "$project_list" | sed -n "$(expr "$project_name" : '\[\([0-9]\+\)\]:.*$')p" | tr / - | encode_dots)"
 			{
 				if ! tmux has-session -t "$session_name"
 				then
@@ -407,9 +400,14 @@ open() {
 		then
 			return
 		else
-			tmux new-session -s "$(printf "$input" | hide_dots )"
+			tmux new-session -s "$(printf "$input" | encode_dots )"
 		fi
 	fi
+}
+
+set_up_session_and_start_watchers() {
+	session_name="$1"
+
 }
 
 set_whxy() {
@@ -417,7 +415,7 @@ set_whxy() {
 	y="$(printf "$window_attributes" | sed -e 's/^.*+\([0-9]\+\)$/\1/')"
 	x="$(printf "$window_attributes" | sed -e 's/^.*+\([0-9]\+\)+.*/\1/')"
 	w="$(printf "$window_attributes" | sed -e 's/^\([0-9]\+\)x.*/\1/')"
-	h="$(printf "$window_attributes" | sed -e 's/^.*x\([0-9\+]\).*/\1/')"
+	h="$(printf "$window_attributes" | sed -e 's/^.*x\([0-9]\+\).*/\1/')"
 }
 
 _dump() {
@@ -429,18 +427,18 @@ _dump() {
 
 	set_whxy $window_attributes_rest
 	cat <<-EOTX
-		unbind M-$tbind_explorer
-		bind M-$tbind_explorer if-shell "command -v wfmux" { display-popup -w $w -h $h -x $x -y $y -E "wfmux explore"; }
+		unbind M-$tbind_explore
+		bind M-$tbind_explore if-shell "command -v wfmux" { display-popup -w $w -h $h -x $x -y $y -E "wfmux explore"; }
 		unbind M-$tbind_ops
 		bind M-$tbind_ops if-shell "command -v wfmux" { display-popup -w $w -h $h -x $x -y $y -E "wfmux ops"; }
 	EOTX
 }
 
-dump() {
+func_dump() {
 	_dump
 }
 
-tmux() {
+func_tmux() {
 	_dump >> "$tmux_conf"
 }
 
@@ -449,7 +447,7 @@ get_project_dir() {
 }
 
 ## open your favorite tui file manager
-explore() {
+func_explore() {
 	# get the name of last used session and translate it into the project directory
 	project_dir=`get_project_dir`
 	if [ -d "$project_dir" -a -d "$session_dir/$project_dir" ]
@@ -459,7 +457,7 @@ explore() {
 }
 
 ## select project files to open
-select() {
+func_select() {
 	new_window=true
 	sh="^${SHELL:-bash}"
 	project_dir=`get_project_dir`
@@ -467,7 +465,7 @@ select() {
 	[ -d "$project_dir" -a -d "$session_dir/$project_dir" ] || return
 
 	_args() {
-		printf "$ignore" | sed 's/\(.*\)/-iname "\1"/' | tr '\n' ' '
+		printf "$ignore" | sed -e 's/\(.*\)/-iname "\1" /' | tr '\n' ' '
 	}
 
 	file="$(find "$project_dir" \( `_args` -prune \) -or \( -type f \) | eval "$searcher")"
@@ -521,7 +519,6 @@ select() {
 	fi
 }
 
-set_up_session_and_start_watchers() { :; }
 switch()   { :; }
 commit()   { :; }
 runner()   { :; }
