halfly implemented display_dashboard function

diff --git a/src/wfmux b/src/wfmux
--- a/src/wfmux
+++ b/src/wfmux
@@ -25,6 +25,20 @@ readonly logo=$(cat <<EOF
                                                                              │
 EOF
 )
+readonly wfmux=$(cat<<EOF
+
+     ┌──────────────┤ WFMUX
+    ┌┴─────────────────────────────────────────────────┐
+    │                                                  │
+    ├───── Input a name for a new tmux session         │
+    │                                                  │
+    ├───── Input f«return» to select a project         │
+    │                                                  │
+    ├───── Input «return» to drop to the terminal      │
+    │                                                  │
+    └──────────────────────────────────────────────────┘
+EOF
+)
 
 wfmux_config="${config_dir%%/}/wfmux/wfmux.conf"
 use_xdg=yes
@@ -65,7 +79,7 @@ Options:
      -h, -help, --help            print this help message.
      -c, -config, --config FILE   load FILE configuration file.
 
-operation_name:
+Operation names:
     open      fuzzyly select a project and open a new tmux session.
     auto      select set of files to watch and bind them to a commmand.
     explore   open your favorite file manager on a popup tmux pane.
@@ -84,7 +98,7 @@ die() {
 }
 
 main() {
-	error_message="is an unrecognized option, please try \`$program --usage'";
+	emessage="is an unrecognized option, please try \`$program --usage'";
 	if [ $# -eq 1 ]; then
 		case $1 in
 			push|commit|select|explore|auto|open)
@@ -97,7 +111,7 @@ main() {
 			-h|-help|--help)
 				usage ;;
 			*)
-				die "$1" "$error_message" ;;
+				die "$1" "$emessage" ;;
 		esac
 	elif [ $# -eq 3 ]; then
 		case $1 in
@@ -111,10 +125,10 @@ main() {
 						check_config_variables
 						eval "$1" ;;
 					*)
-						die "$2" "$error_message" ;;
+						die "$2" "$emessage" ;;
 				esac ;;
 			*)
-				die "$1" "$error_message" ;;
+				die "$1" "$emessage" ;;
 		esac
 	else
 		die "invalid option count, please try \`$program --usage'"
@@ -126,13 +140,13 @@ main() {
 ## We won't have to rely on `set -u`, we would want to output an error
 ## message if one of these variables aren't set/sane.
 check_config_variables() {
-	error_message="$program: ('$config_file'): "
+	emessage="$program: ('$config_file'): "
 	window_regex='^[[:digit:]]+x[[:digit:]]+\+[[:digit:]]+\+[[:digit:]]+$'
 
 	for parameter in use_xdg automater searcher explorer window_attributes_rest \
 	                 window_attributes_file_selector project_directory; do
 		eval "parameter=\${$parameter:-NaN}"
-		[ "$parameter" = NaN ] && die "$error_message" "'$parameter' isn't set"
+		[ "$parameter" = NaN ] && die "$emessage" "'$parameter' isn't set"
 	done
 	
 	## check for sane values
@@ -140,49 +154,68 @@ check_config_variables() {
 		{ who=window_attributes_rest; printf '%s' "$window_attributes_rest" | grep -Eq "$window_regex"; }                   &&
 		{ who=window_attributes_file_selector; printf '%s' "$window_attributes_file_selector" | grep -Eq "$window_regex"; } &&
 		{ who=use_xdg; printf '%s' "$use_xdg" | grep -Eq '^true|false$'; }
-	) || die "$error_message" "content of '$who' isn't valid"
+	) || die "$emessage" "content of '$who' isn't valid"
 
 	# now we should expect executable binaries/sh-functions/aliases
 	OLD_IFS=$IFS; IFS=$':'
 	for dependency in explorer automater searcher; do
 		found=false
 		for bin_dir in $PATH; do [ -x "${bin_dir%%/}/$dependency" ] && { found=true; break; }; done
-		[ $found = false ] && die "$error_message" "'$dependency' isn't found"
+		[ $found = false ] && die "$emessage" "'$dependency' isn't found"
 	done
 
-	# check if project dirs exist
+	# check if project dirs exist and are readable
 	IFS=$'\n'
 	for dir in $project_directory; do
-		[ -d "$dir" ] || die "$error_message" "'$dir' isn't a directory"
-		[ -r "$dir" ] || die "$error_message" "cannot list content of '$dir'"
+		[ -d "$dir" ] || die "$emessage" "'$dir' isn't a directory"
+		[ -r "$dir" ] || die "$emessage" "cannot list content of '$dir'"
 	done
 	IFS=$OLD_IFS
 }
 
-dashboard() {
-	:;
+display_dashboard() {
+	max_line="awk 'BEGIN{len = 0}; {nlen = length(\$0); if (nlen > len) len = nlen;}; END{print len}'"
+	logo_h=$(printf '%s' "$logo" | wc -l)
+	logo_w=$(printf '%s' "$logo" | eval "$max_line")
+	read term_w term_h < $(stty size)
+	x=$(expr $term_h / 2 - $logo_h / 2)
+	y=$(expr $term_w / 2 - $logo_h / 2)
+
+	gen_key_helper() {
+		cat <<-EOF
+			The following are tmux bindings related to WFMUX.
+
+			M-$tbind_select:   fuzzyly open project files
+			M-$tbind_explorer: open file manager
+			M-$tbind_ops:      fuzzyly select other wfmux operations
+		EOF
+	}
+	_print() { printf '\033[%s;%sf%s' "$1" "$2" "$3"; }
+
+	# save initial terminal setting which is to be set back after exiting dashboard
+	init_stty=$(stty -g)
+	stty -echo
+
+	while read line; do _print $x $y "$line"; y=$((y+1)); done < $(printf '%s' "$logo")
+	gen_w=$(gen_key_helper | eval "$max")
+	[ $gen_w -gt $logo_w ] &&
+	gen_x=$(expr )         ||
+	gen_x=$(expr )
+	gen_key_helper | while read line; do _print $gen_x $y "$line"; y=$((y+1)); done
+
+	# usefull for undoing terminal device settings
+	export ON_DASHBOARD=true
 }
+
+# based on tmux keybindings configuration, generate help message
 
 ## select a project and open a tmux session
 open() {
-	if tmux list-sessions >/dev/null 2>&1
-	then
+	tmux list-sessions >/dev/null 2>&1 && {
 		printf '%s\n\n' "Choose an existing session to attach"
-		tmux list-sessions | awk '{print NR") "$0}'
-	fi
-	cat<<EOF
-
-	 ┌──────────────┤ WFMUX
-	┌┴─────────────────────────────────────────────────┐
-	│                                                  │
-	├───── Input a name for a new tmux session         │
-	│                                                  │
-	├───── Input f«return» to select a project         │
-	│                                                  │
-	├───── Input «return» to drop to the terminal      │
-	│                                                  │
-	└──────────────────────────────────────────────────┘
-EOF
+		tmux list-sessions | awk '{print "("NR") "$0}'
+	}
+	printf '%s\n' "$wfmux"
 	read -p "»»» " input
 	tput clear
 
@@ -190,11 +223,9 @@ EOF
 		session_name=$(tmux list-sessions -F '#S' | sed -n "${input}p")
 		[ -n "$session_name" ] && tmux attach-session -t "$session_name"
 	else
-		if [ "$input" = f -o "$input" = F ]
-		then
-			if [ `printf '%s' "$project_directory" | wc -l` -ne 1 ]; then
-				project_directory=$(printf '%s' "$project_directory" | eval "$searcher")
-			fi
+		if [ "$input" = f -o "$input" = F ]; then
+			[ `printf '%s' "$project_directory" | wc -l` -ne 1 ] &&
+			project_directory=$(printf '%s' "$project_directory" | eval "$searcher")
 
 			[ -n "$project_directory" ] || return
 			[ -r "$project_directory" ] || return
@@ -211,7 +242,6 @@ EOF
 		else
 			tmux new-session -s "$(printf '%s' "$input" | tr _ '\034' | tr . _)"
 		fi
-
 	fi
 }
 
