refine code and fix some issues with the specification of the watcher file(should take into consideration its state, 0/1 infront of s[-+])

diff --git a/src/wfmux b/src/wfmux
--- a/src/wfmux
+++ b/src/wfmux
@@ -415,38 +415,6 @@ func_nsession() {
 	__new_session
 }
 
-__start_watcher() {
-	local project_session=$2
-	local one_shot=${1%%(*}
-	local cmd=${1#?(*)}
-	local watcher_name=${1%%)*}
-
-	watcher_name=${1#?(}
-
-	# You would be seeing the std(out|err) of watchers via named-pipes
-	local fifo="$project_session/fifos/$watcher_name.fifo"
-
-	test -p "$fifo" || mkfifo "$fifo"
-	{ 
-		trap '' HUP
-		if [ $one_shot = 1 ]
-		then
-			# for self restarting programs(like framework developement server, etc.)
-			eval "$cmd"
-		else
-			cat "$project_session/watch" \
-			| sed -ne "/^s+0\[$watcher_name\]:/,/^e\[$watcher_name\]/p" \
-			| tail -n +2 \
-			| sed '$d' \
-			| case $RUNNER in
-			   entr) entr -nr "$cmd" ;;
-			   *) : ;;
-			  esac >"$fifo"
-		fi
-	} >"$fifo" 2>&1 &
-
-	printf "$!" >"$project_session/$watcher_name.pid"
-}
 
 __setup_session() {
 	local project_dir=$1
@@ -825,11 +793,39 @@ __push() {
 	fi
 }
 
+__start_watcher() {
+	local project_session=$2 one_shot=${1%%(*} cmd=${1#?(*)} watcher_name=${1%%)*}
+
+	watcher_name=${1#?(}
+
+	# You would be seeing the std(out|err) of watchers via named-pipes
+	local fifo="$project_session/fifos/$watcher_name.fifo"
+
+	test -p "$fifo" || mkfifo "$fifo"
+	{ 
+		trap '' HUP
+		if [ $one_shot = 1 ]
+		then
+			# for self restarting programs(like framework developement server, etc.)
+			eval "$cmd"
+		else
+			cat "$project_session/watch" \
+			| sed -ne "/^s+0\[$watcher_name\]:/,/^e\[$watcher_name\]/p" \
+			| tail -n +2 \
+			| sed '$d' \
+			| case $RUNNER in
+			   entr) entr -nr "$cmd" ;;
+			   *) : ;;
+			  esac >"$fifo"
+		fi
+	} >"$fifo" 2>&1 &
+
+	printf "$!" >"$project_session/$watcher_name.pid"
+}
+
 # Add a new watcher to the watcher list
 func_awatcher() {
-	local watcher_name
-	local watch_config="$SESSION_DIR/`__get_cur_session`/watch"
-	local project_dir=`__get_project_dir`
+	local watcher_name watch_config="$SESSION_DIR/`__get_cur_session`/watch" project_dir=`__get_project_dir`
 
 	printf "Give a name to your watcher: "
 	read watcher_name
@@ -840,18 +836,25 @@ func_awatcher() {
 	if [ -n "$watcher_name" ]
 	then
 		# Check if this name already exists in the watcher list
-		if [ -f "$watch_config" ]
-		then
-			cat "$watch_config" | grep -q "s[-+]:\[$watcher_name\]" && return
+		if [ -f "$watch_config" ]; then
+			cat "$watch_config" | grep -q "^s[-+][01]:\[$watcher_name\]" && return
 		fi
 
-		local files=$(
-			args=$(printf "$IGNORE" | sed -e '${ s/\(.*\)/-name "\1"/; q; }; 1,${ s/\(.*\)/-name "\1" -or /; }' | tr '\n' ' ')
-			eval "find '$project_dir' \( $args \) -prune -or -type f -print | sed -e 's,^$project_dir/,,' | $SEARCHER"
-		)
+		__get_files() {
+			local args=$(
+				printf "$IGNORE" |
+				sed -e '
+					${ s/\(.*\)/-name "\1"/; q; };
+					1,${ s/\(.*\)/-name "\1" -or /; }
+			    ' |
+				tr '\n' ' '
+			)
+		    eval "find '$project_dir' \( $args \) -prune -or -type f -print | sed -e 's,^$project_dir/,,' | $SEARCHER"
+		}
 
-		if [ -n "$files" ]
-		then
+		local files=`__get_files`
+		if [ -n "$files" ]; then
+
 			printf "\033[1;4m"
 			if [ -r "$COMMANDS" ]
 			then
@@ -895,22 +898,23 @@ func_rwatcher() {
 
 	test -r "$watch_config" -a -s "$watch_config" || return
 
-	local watcher_name=$(cat "$watch_config" | sed -ne 's/^s[-+]\[\(\w*\)\]:.*$/\1/p')
-	if [ -n "$watcher_name" ]
+	local watcher_names=$(cat "$watch_config" | sed -ne 's/^s[-+]\[\(\w*\)\]:.*$/\1/p')
+	if [ -n "$watcher_names" ]
 	then
-		watcher_name=$(printf "$watcher_name" | eval "$SEARCHER")
+		local watcher_name=$(printf "$watcher_names" | eval "$SEARCHER")
 		if [ -n "$watcher_name" ]
 		then
 			printf "\033[1;4m"
 			cat "$watch_config" | grep -q "^e\[$watcher_name\]"
+
 			if [ $? -eq 0 ]
 			then
-				sed -i "/^s+\[$watcher_name\]:/,/^e\[$watcher_name\]/d" "$watch_config"
+				sed -i "/^s..\[$watcher_name\]:/,/^e\[$watcher_name\]/d" "$watch_config"
 				if [ $? -eq 0 ]
 				then
-					if [ -r "$project_session/$watcher_name.pid" ]
+					if [ -r "$project_session/fifos/$watcher_name.pid" ]
 					then
-						pid=$(cat "$project_session/$watcher_name.pid")
+						pid=$(cat "$project_session/fifos/$watcher_name.pid")
 						kill -KILL "$pid" >/dev/null 2>&1
 					fi
 					printf "\033[1;3${DASH_COLOR}m"
@@ -933,27 +937,20 @@ func_rwatcher() {
 }
 
 __ed_watcher() {
-	local cur_session=$1
-	[ -z "$cur_session" ] && return
+	local watch_config="$1/watch"
 
-	local watch_config="$SESSION_DIR/$cur_session/watch"
 	if [ -r "$watch_config" -a -s "$watch_config" ]
 	then
-		local watcher_name=$(cat "$watch_config" | sed -ne 's/^s[-+][01]\[\(\w*\)\]:.*$/\1/p')
-
-		if [ -n "$watcher_name" ]
+		local watcher_names=$(cat "$watch_config" | sed -ne 's/^s[-+][01]\[\(\w*\)\]:.*$/\1/p')
+		if [ -n "$watcher_names" ]
 		then
-			watcher_name=$(printf "$watcher_name" | eval "$SEARCHER")
+			local watcher_name=$(printf "$watcher_names" | eval "$SEARCHER")
 			if [ -n "$watcher_name" ]
 			then
-				local state=$2
-				local to=disable
-				[ x$state = x"+" ] && to=enable
-				sed -ie "s/^s.\(.\[$watcher_name\]\)/^s$state\1/" "$watch_config"
-
+				sed -ie "s/^s.\(.\[$watcher_name\]\)/^s$2\1/" "$watch_config"
 			fi
 		else
-			printf "No watcher could be found\n"
+			printf "No watcher were found\n"
 		fi
 	fi
 }
@@ -962,24 +959,27 @@ __ed_watcher() {
 # This operation sets on watchers to be runned upon session's startup.
 func_ewatcher() {
 	local cur_session=`__get_cur_session`
+	local project_session="$SESSION_DIR/$cur_session"
+	local watch_file="$project_session/watch"
+
 	[ -z "$cur_session" ] && return
 
 	printf "\033[4m"
 
-	local watcher_name=$(__ed_watcher "$cur_session" +)
+	local watcher_name=$(__ed_watcher "$watch_file" +)
 	if [ $? -eq 0 ]
 	then
-		local pid_file="$SESSION_DIR/$cur_session/fifos/$watcher_name.pid"
+		local pid_file="$project_session/fifos/$watcher_name.pid"
 
 		if ! test -s "$pid_file" ||
-		   ! ps aux | grep -q "^$(cat "$pid_file") "
+		   ! ps a | grep -q "^[\t ]\+$(cat "$pid_file")"
 		then
-			local pairs=$(cat "$SESSION_DIR/$cur_session/watch" | sed -ne 's/^s+\(.\)\[\(.*\)\]: *\(.\+\) *$/\1(\2)\3/p')
-			__start_watcher "$pairs" "$SESSION_DIR/$cur_session"
+			local pairs=$(cat "$watch_file" | sed -ne 's/^s+\(.\)\[\(.*\)\]: *\(.\+\) *$/\1(\2)\3/p')
+			__start_watcher "$pairs" "$project_session"
 		fi
 
 		printf "\033[1;3${DASH_COLOR}m"
-		printf "Watcher '$watcher_name' ${to}d.\n"
+		printf "Watcher '$watcher_name' enabled.\n"
 		printf "${UNSET_ANSI}${UNSET_ANSI}"
 	else
 		printf "\033[1;31m"
@@ -991,13 +991,44 @@ func_ewatcher() {
 
 # Disable watchers, should be runned within an existing wfmux tmux session.
 # This operation sets off watchers so that they cannot run when a new wfmux
-# tmux session is initiated
+# tmux session is initiated either via `func_open' or `func_nsession'
 func_rwatchers() {
-	__ed_watcher -
+	local cur_session=`__get_cur_session`
+	local project_session="$SESSION_DIR/$cur_session"
+	local watch_file="$project_session/watch"
+
+	[ -z "$cur_session" ] && return
+
+	printf "\033[4m"
+
+	local watcher_name=$(__ed_watcher "$watch_file" -)
+	if [ $? -eq 0 ]
+	then
+		printf "\033[1;3${DASH_COLOR}m"
+		printf "Watcher '$watcher_name' disabled.\n"
+		printf "${UNSET_ANSI}${UNSET_ANSI}"
+	else
+		printf "\033[1;31m"
+		printf "Could not disable watcher '$watcher_name'\n"
+	fi
 }
 
 # Fancy view of the state of all watchers belonging to the project in question
+# Definition of the view
+#             --[ project_name ]--
+#    PID:          not running(red), running(dash_color)
+#    WATCHER_NAME: disable(red), enabled(dash_color)
+#    o/m         : o, not monitored by $runner otherwise m
+#
+#    WATCHER_NAME   PID    o/m  COMMAND
+#    watcher_name_1 pid_1  o    command_1
+#    watcher_name_2 pid_2  m    command_2
+#    watcher_name_3 pid_3  m    command_3
 func_view() {
+	:;
+}
+
+func_ksession() {
 	:;
 }
 
